TrajectoryPlannerROS:

  # Robot Configuration Parameters
  acc_lim_theta: 3.0
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  
  max_vel_x: 0.4
  min_vel_x: 0.0 # 0.1 by default.
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  escape_vel: -0.1

  holonomic_robot: false

  y_vels: [-0.3, -0.1, 0.1, 0.3] # Default

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.025 # Default
  angular_sim_granularity:  0.025 # Default
  vx_samples: 20
  vtheta_samples: 20
  controller_frequency: 20 # Default

  # Trajectory Scoring Parameters
  meter_scoring: false # Meter or Cell (default)
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.02
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.1
  dwa: false
  publish_cost_grid_pc: false
  global_frame_id: odom

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  prune_plan: true