base_global_planner: global_planner/GlobalPlanner
#base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS
#base_global_planner: "navfn/NavfnROS"

shutdown_costmaps: false

controller_frequency: 15.0
controller_patience: 10.0

planner_frequency: 1.0
planner_patience: 20.0

# conservative_reset_dist: 3.0

oscillation_timeout: 10.0
oscillation_distance: 0.1
max_planning_retries: 10

recovery_behavior_enabled: true
clearing_rotation_allowed: false

recovery_behaviors:
  #- name: 'super_conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset1'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  # - name: 'clearing_rotation1'
    # type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
    #type: 'rotate_recovery/RotateRecovery'

#super_conservative_reset1:
  #reset_distance: 3.0
#conservative_reset1:
  #reset_distance: 1.5
aggressive_reset1:
  reset_distance: 3.0
#super_conservative_reset2:
  #reset_distance: 3.0
#conservative_reset2:
  #reset_distance: 1.5
#aggressive_reset2:
  #reset_distance: 0.0