base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 10.0

planner_frequency: 1.0
planner_patience: 20.0

oscillation_timeout: 10.0
oscillation_distance: 0.1
max_planning_retries: 10

recovery_behavior_enabled: true
clearing_rotation_allowed: true
conservative_reset_dist: 3.0