scan_filter_chain:

#########################################################
###          _______       0 deg      _______
###         |angle_1|       |        |angle_2|
###          """""""        |         """""""
###                        +|-     
###                         |
###                         |
###                       _____
###                      |LIDAR|
###                       """""
###
###
###
###           _______                 _______
###          |angle_3|               |angle_4|
###           """""""                 """""""
#########################################################


- name: angle_1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.588
    upper_angle: 0.686

- name: angle_2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 5.597
    upper_angle: 5.695

- name: angle_3
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 2.455
    upper_angle: 2.554

- name: angle_4
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 3.729
    upper_angle: 3.828

- name: angle_5
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.129
    upper_angle: 2.270

- name: angle_6
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 4.012
    upper_angle: 5.153