scan_filter_chain:

#########################################################
###          _______       0 deg      _______
###         |angle_1|       |        |angle_2|
###          """""""        |         """""""
###                        +|-     
###                         |
###                         |
###                       _____
###                      |LIDAR|
###                       """""
###
###
###
###           _______                 _______
###          |angle_3|               |angle_4|
###           """""""                 """""""
#########################################################


- name: angle_1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.530
    upper_angle: 0.695

- name: angle_2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.686 #3.729
    upper_angle: -0.548 #3.828

- name: angle_3
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 2.455
    upper_angle: 2.610

- name: angle_4
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -2.578
    upper_angle: -2.455

- name: angle_5
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.129
    upper_angle: 2.270

- name: angle_6
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -2.270 #-2.011 #4.012
    upper_angle: -1.129 #-0.870 #5.153

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 1
    max_range: 2.0
    max_range_difference: 0.1
    filter_window: 6