scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_scan
    max_x: 0.26
    max_y: 0.20
    max_z: 0.7
    min_x: -0.26
    min_y: -0.20
    min_z: -0.7
    invert: false

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 1
    max_range: 2.0
    max_range_difference: 0.1
    filter_window: 6